QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 2000 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 5000 } } },
	-- judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 10000 } } },
	-- lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 5000 } } },
	-- reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 5000 } } },
	-- trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 5000 } } },
	-- tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 5000 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 5000 } } },
	-- vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 5000 } } },
	-- hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 5000 } } },

	police = {
		label = 'Police',
		type = 'police',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 5000 },
			['1'] = { name = 'Officer', payment = 7500 },
			['2'] = { name = 'Sergeant', payment = 10000 },
			['3'] = { name = 'Lieutenant', payment = 12500 },
			['4'] = { name = 'Chief', isboss = true, payment = 15000 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 5000 },
			['1'] = { name = 'Paramedic', payment = 7500 },
			['2'] = { name = 'Doctor', payment = 10000 },
			['3'] = { name = 'Surgeon', payment = 12500 },
			['4'] = { name = 'Chief', isboss = true, payment = 15000 },
		},
	},
	-- realestate = {
	-- 	label = 'Real Estate',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
	-- 		['0'] = { name = 'Recruit', payment = 5000 },
	-- 		['1'] = { name = 'House Sales', payment = 7500 },
	-- 		['2'] = { name = 'Business Sales', payment = 10000 },
	-- 		['3'] = { name = 'Broker', payment = 12500 },
	-- 		['4'] = { name = 'Manager', isboss = true, payment = 15000 },
	-- 	},
	-- },
	-- taxi = {
	-- 	label = 'Taxi',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
	-- 		['0'] = { name = 'Recruit', payment = 5000 },
	-- 		['1'] = { name = 'Driver', payment = 7500 },
	-- 		['2'] = { name = 'Event Driver', payment = 10000 },
	-- 		['3'] = { name = 'Sales', payment = 12500 },
	-- 		['4'] = { name = 'Manager', isboss = true, payment = 15000 },
	-- 	},
	-- },
	cardealer = {
		label = 'Dealer',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 5000 },
			['1'] = { name = 'Showroom Sales', payment = 7500 },
			['2'] = { name = 'Business Sales', payment = 10000 },
			['3'] = { name = 'Finance', payment = 12500 },
			['4'] = { name = 'Manager', isboss = true, payment = 15000 },
		},
	},
	mechanic = {
		label = 'Mekanik',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 5000 },
			['1'] = { name = 'Novice', payment = 7500 },
			['2'] = { name = 'Experienced', payment = 10000 },
			['3'] = { name = 'Advanced', payment = 12500 },
			['4'] = { name = 'Manager', isboss = true, payment = 15000 },
		},
	},
	-- mechanic2 = {
	-- 	label = 'LS Customs',
	-- 	type = 'mechanic',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
	-- 		['0'] = { name = 'Recruit', payment = 50 },
	-- 		['1'] = { name = 'Novice', payment = 75 },
	-- 		['2'] = { name = 'Experienced', payment = 100 },
	-- 		['3'] = { name = 'Advanced', payment = 125 },
	-- 		['4'] = { name = 'Manager', isboss = true, payment = 150 },
	-- 	},
	-- },
	-- mechanic3 = {
	-- 	label = 'LS Customs',
	-- 	type = 'mechanic',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
	-- 		['0'] = { name = 'Recruit', payment = 50 },
	-- 		['1'] = { name = 'Novice', payment = 75 },
	-- 		['2'] = { name = 'Experienced', payment = 100 },
	-- 		['3'] = { name = 'Advanced', payment = 125 },
	-- 		['4'] = { name = 'Manager', isboss = true, payment = 150 },
	-- 	},
	-- },
	-- beeker = {
	-- 	label = 'Beeker\'s Garage',
	-- 	type = 'mechanic',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
	-- 		['0'] = { name = 'Recruit', payment = 50 },
	-- 		['1'] = { name = 'Novice', payment = 75 },
	-- 		['2'] = { name = 'Experienced', payment = 100 },
	-- 		['3'] = { name = 'Advanced', payment = 125 },
	-- 		['4'] = { name = 'Manager', isboss = true, payment = 150 },
	-- 	},
	-- },
	-- bennys = {
	-- 	label = 'Benny\'s Original Motor Works',
	-- 	type = 'mechanic',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
	-- 		['0'] = { name = 'Recruit', payment = 50 },
	-- 		['1'] = { name = 'Novice', payment = 75 },
	-- 		['2'] = { name = 'Experienced', payment = 100 },
	-- 		['3'] = { name = 'Advanced', payment = 125 },
	-- 		['4'] = { name = 'Manager', isboss = true, payment = 150 },
	-- 	},
	-- },
}
